
CREATE TABLE IF NOT EXISTS members (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  country VARCHAR(100) NOT NULL,
  date_joined DATETIME DEFAULT CURRENT_TIMESTAMP
);
